### ISSUE TITLE
Python3に対応している(はずの/かもしれない)パッケージの `PYTHON_COMPAT` にPython2しかないとき

### ISSUE THREAD

**Issue by lo48576** [gentoojp/issues#10]
長くなってすみません。

# 概要
- `net-im/pidgin-2.12.0` と `net-libs/gupnp-1.0.1` がupstreamでは(おそらく？)python3対応しているらしいのに、ebuildの `PYTHON_COMPAT` ではpython2.7しか指定されていない
  * 公式で対応しているとは言っていないが、issue trackerとかで調べてみる限りではそんな雰囲気
- `PYTHON_COMPAT` を弄ったら、emergeはできた
  * 正しく動くとは言ってない
- できれば公式リポジトリで `PYTHON_COMPAT` をいい感じにしてほしい

# 経緯
1. Pidgin 2.12 (`net-im/pidgin-2.12.0`) がリリースされたと聞き、入れてみようと思い立った
2. [ebuild](https://github.com/gentoo-mirror/gentoo/blob/4ff8d478c26d5366eb8f1f62fba37e2a081513c6/net-im/pidgin/pidgin-2.12.0.ebuild#L7)で `PYTHON_COMPAT=( python2_7 )` と指定されていたが、Python3で入れたい
  * 主に宗教的な理由で、 `make.conf` で `USE="-python"`, `PYTHON_TARGETS="python3_5"`, `PYTHON_SINGLE_TARGET="python3_5"` していて、どうしてもPython2が必要なときだけ `package.use` で調整しています
  * gentooのbugz ( https://bugs.gentoo.org/buglist.cgi?quicksearch=pidgin%20python ) で調べてみたが、pidginでのpythonのバージョンについて話している人は居なさげ
3. [#15695 (Python 3 compatibility) – Pidgin](https://developer.pidgin.im/ticket/15695) のようなticketが見付かり、どうやら随分昔からPidginはPython3対応しているらしいと気付く
4. ローカルのoverlayで `PYTHON_COMPAT` に `python3_5` を追加し `emerge -pv` するも、 `net-libs/gupnp-1.0.1` でPython2.7が必要らしく失敗 (ログ1)
5. 調べてみると、gupnpもPython3に対応しているらしい
  * [Bug 1192093 – Switch gupnp to Python 3](https://bugzilla.redhat.com/show_bug.cgi?id=1192093#c0)
  * [本家gnomeのページ](https://wiki.gnome.org/Projects/GUPnP)や[README](https://git.gnome.org/browse/gupnp/tree/README?h=gupnp-1.0)等からはPythonのバージョンに関する記述を見付けられなかった
  * gentooのbugzにも情報なさげ( https://bugs.gentoo.org/buglist.cgi?quicksearch=gupnp )
6. [gupnpのebuild](https://github.com/gentoo-mirror/gentoo/blob/stable/net-libs/gupnp/gupnp-1.0.1.ebuild#L7)も同じくローカルのoverlayで `PYTHON_COMPAT` に `python3_5` を追加
7. 以上のように改変した `pidgin-2.12.0.ebuild` と `gupnp-1.0.1.ebuild` で、少なくともemergeには成功した
  * 動作確認等はしていないので、これから実際に使ってみて、駄目そうなら諦めてpython2を許可するつもりでいます

ログ1:
```
$ PYTHON_TARGETS="python3_5" emerge -pv pidgin

These are the packages that would be merged, in order:

Calculating dependencies / * Missing digest for '/usr/local/larry-overlay/net-libs/gupnp/gupnp-1.0.1.ebuild'
 * Missing digest for '/usr/local/larry-overlay/net-libs/gupnp/gupnp-0.20.18.ebuild'
... done!

!!! The ebuild selected to satisfy ">=net-libs/gupnp-0.20.10[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,$
bi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]" has unmet requirements.
- net-libs/gupnp-1.0.1::gentoo USE="introspection -connman -networkmanager" ABI_X86="64 -32 -x32" PYTHON_TARGETS="-python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    python_targets_python2_7

  The above constraints are a subset of the following complete expression:
    any-of ( python_targets_python2_7 ) at-most-one-of ( connman networkmanager )

(dependency required by "net-libs/gupnp-igd-0.2.4::gentoo" [ebuild])
(dependency required by "net-libs/libnice-0.1.13::gentoo[upnp]" [ebuild])
(dependency required by "media-plugins/gst-plugins-libnice-0.1.13-r100::gentoo" [ebuild])
(dependency required by "net-libs/farstream-0.2.8-r1::gentoo" [ebuild])
(dependency required by "net-im/pidgin-2.12.0::larry-overlay[gstreamer]" [ebuild])
(dependency required by "pidgin" [argument])
```
(`larry-overlay` は私のローカルオーバーレイです)

# 本題
## 前提
- 公式に Python3 に対応しているのか不明
  * 調べてはみたが力及ばず
- もし公式に対応しているとして、何をもって問題なく動作しているとするか知らない
  * 単にそのことについて私に知識がない
- 対応しているのであれば、gentoo公式リポジトリでも `PYTHON_COMPAT` を更新してほしい
  * 無理/厳しいならoverlayで一応我慢できる

## 質問
- このような曖昧な状態でbugzillaにticketを立ててよいものでしょうか？
  * 良いならそれで《完》
- 駄目なら、何をすべきでしょうか？
  * bugzilla以外のもっとカジュアルな場がある？
  * 自分である程度の安定性を確認してからbugzillaへ行く必要がある？
  * 或いは黙して待つ？

**Comment by lo48576** [comment]
# 追記1
[#16992 (Port libpurple Python scripts to pydbus and Python 2+3) – Pidgin](https://developer.pidgin.im/ticket/16992)
ごめんなさい、今こんなものを見付けたので、もしかするとpidginの方はPython3非対応で正解かもしれないです。

**Comment by aliceinwire** [comment]
net-im/pidginはpython3対応になりましたのこのissue閉じます。間違ったらも一回開いてください。
