### ISSUE TITLE
'"`UNIQ--pre-00000001-QINU`"'について

### ISSUE THREAD

**Issue by akapy** [gentoojp/issues#12]
https://wiki.gentoo.org/wiki/Systemd/ja を読みながらsystemdなインストールを行ってる途中です。
カーネル設定で.configの中身を検索置換するための呪文だと思うのですが、
　　'"`UNIQ--pre-00000001-QINU`"'
ってどう使うものなんでしょうか？

**Comment by orumin** [comment]
それはおそらく Media Wiki の不具合で意図せず出力された文字列ですので元々の文字列とは異なるかと思われます。

cf. https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/issues/105

**Comment by orumin** [comment]
原文だと

```
Gentoo Linux --->
   Support for init systems, system and service managers --->
      [*] systemd
```

みたいですね

https://wiki.gentoo.org/wiki/Systemd/en

**Comment by akapy** [comment]
そうなんですか。ありがとうございます。
