### ISSUE TITLE
GentooJPのURLが gr.jp のままになっている

### ISSUE THREAD

**Issue by mazgi** [gentoojp/issues#5]
`gentoo.gr.jp` は廃止済みなので `www.gentoo.jp` に修正していただけましたらさいわいでございます！
### refs
- https://github.com/gentoojp
- http://www.gentoo.jp/jpnews/main/20151115-shutdown-gentoo-gr-jp.html

<img width="359" alt="screen shot 2016-08-12 at 5 35 11 pm" src="https://cloud.githubusercontent.com/assets/194222/17617133/5bc5ea5c-60b3-11e6-8b17-7a93d21653ed.png">

**Comment by kjmkznr** [comment]
Thanks!

Fixed.

**Comment by mazgi** [comment]
thx!
