### ISSUE TITLE
gnucash が guile-1.8 に依存しているが guile-2.0.12-r1:12/22 が存在する

### ISSUE THREAD

**Issue by lo48576** [gentoojp/issues#6]
app-office/gnucash-2.6.13 をemergeしようとしたところ、以下のエラーで失敗しました。

[build.log.txt](https://github.com/gentoojp/issues/files/423946/build.log.txt)
[config.log.txt](https://github.com/gentoojp/issues/files/423947/config.log.txt)

(build.log 抜粋)

```
checking for guile-1.8 >= 1.8.5... no
Package guile-1.8 was not found in the pkg-config search path. Perhaps you should add the directory containing `guile-1.8.pc' to the PKG_CONFIG_PATH environment variable No package 'guile-1.8' found
configure: error: Library requirements (guile-1.8 >= 1.8.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a non standard prefix so pkg-config can find them.
```

gnucash-2.6.13 は `>=dev-scheme/guile-1.8.3:12[deprecated,regex]` に依存していますが、 `dev-scheme/guile-2.0.12-r1:12/22` が存在する(そして私のマシンではそちらがインストールされている)ため、configureで `guile-1.8.pc` が発見できず失敗してるようです。

guileのslot指定とgnucashのebuild、どちらが修正されるべきなのかわかりませんが、報告いたします。

**Comment by naota** [comment]
本家bugzだと https://bugs.gentoo.org/show_bug.cgi?id=590536
gnucash upstreamだと https://github.com/Gnucash/gnucash/pull/98
にpatchが出ていますね。

gnucash ebuildを --with-guile=2.0 にして、 2.0対応patchを当てているようです。

**Comment by lo48576** [comment]
本家bugzillaの存在を失念していました……

`sudo EXTRA_ECONF=--with-guile=2.0 emerge -uv gnucash` で横着しようとしましたが、やはり[本家スレ同様の場所](https://bugs.gentoo.org/show_bug.cgi?id=590536#c6)で失敗したので、upstreamが対応するまで素直に待とうと思います。

ありがとうございました。
