### ISSUE TITLE
grub2のインストールについて

### ISSUE THREAD

**Issue by i-id** [gentoojp/issues#8]
grub2設定でgrub-install /dev/sdaを実行するとbashエラーとなってしまいます。
emerge --ask --verbose sys-boot/grub:2　↓
echo 'GRUB_PLATFORMS="efi-64"' >> /etc/portage/make.conf　↓
emerge --ask sys-boot/grub:2　↓
emerge --ask --update --newuse --verbose sys-boot/grub:2　↓
grub-install /dev/sdaでNG

他のwebページを参考に
emerge sys-boot/grub　↓
grub-install /dev/sdaでNG

grub-install /dev/sdaがなぜ実行できないのか教えていただけないでしょうか？
grub-install /dev/sda1の様にbootを指定して実行でしょうか？

###fstabの設定情報
/dev/sda1  /boot  ext2 defauilts.noatime 0 2
/dev/sda2  none  swap sw
/dev/sda3  /         ext4   noatime               0 1
###

**Comment by mazgi** [comment]
@i-id なにはともあれコンソールログがないと皆さんアドバイスが難しいと思います。
https://github.com/gentoojp/issues/issues/7#issuecomment-275039165 のようにしていただくか、インストール対象のPC(VAIOでしたよね?)にSSHでログインしてコマンドを実行し、SSH元のPCでコンソール出力をコピる等してみるのはいかがでしょうか?

あとコマンド実行結果などは ⏬ のように `` ` `` 3つで括って書くと綺麗に成形できます。

````
```
$ emerge --ask --verbose sys-boot/grub:2
```
````

`github merkdown` 等でググるとより詳しい情報が得られます。

@aliceinwire  ここはヘルプセンターではないと思うのですが https://github.com/gentoojp になにか質問用のrepo作るorSlackでやりとりしますか?

**Comment by i-id** [comment]
mazgiさん
ありがとうございます。
logについては行数が多かったので添付しませんでした。しかし仰る通りだと思いますので
以後気を付けます。
質問場所も間違えていたようなので、クローズします。
色々教えていただきありがとうございました。

**Comment by unarist** [comment]
@mazgi 「Gentooのバグレポート、**疑問、質問**に日本語で対応するためのリポジトリ」ってそういうことではないんでしょうか https://github.com/gentoojp/issues/blob/master/README.md

**Comment by mazgi** [comment]
@i-id おっと・・・

> @aliceinwire ここはヘルプセンターではないと思うのですが https://github.com/gentoojp になにか質問用のrepo作るorSlackでやりとりしますか?

これは「この先どうする?」という相談なので今回の質問に対してどうこうという意図ではなかったです。
もし否定的に聞こえてしまったのでしたらすみません。

logについては、「行数多いので迷惑になるかも」と気を遣われる気持ちはわかります。
ただやはり問題解決には必要なので、issueであれメーリングリストであれslackであれ、特に慣れない分野に関してはできるだけ多くの情報をそのまま出すのが解決の近道だと思います。
例えば[gist](https://gist.github.com/)等に貼る方法もありますので、量が多いこと自体を気にする必要はないと思います。

**Comment by mazgi** [comment]
> 「Gentooのバグレポート、疑問、質問に日本語で対応するためのリポジトリ」

oh...じゃあここがヘルプセンターで合ってる・・・?
@i-id ｽﾐﾏｾﾝｽﾐﾏｾﾝ

**Comment by mazgi** [comment]
@i-id 

> echo 'GRUB_PLATFORMS="efi-64"' >> /etc/portage/make.conf　↓

これはUEFI向けの設定ですが合っていますか?
それとも特に意識せずドキュメントを頼りに進めている感じでしょうか?

> grub-install /dev/sdaでNG

ここのコンソール出力がほしいです。
(取得が難しければさいあく写真撮って添付でも)

**Comment by mazgi** [comment]
> /dev/sda1 /boot ext2 defauilts.noatime 0 2

って書いてあるからBIOS向けにインストールしている・・・？

**Comment by i-id** [comment]
ご連絡ありがとうございます。
お手数をお掛けしますが、再度教えてください。
先程ドキュメント通りに実施した時のlogファイルと設定情報をアップします。
またgrub-install /dev/sdaを実行した際に出たエラーは
掲載時：
bash :■　■　■ grub-install
先程実施した時:
grub-install:■　■　■:/usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory

宜しくお願いいたします。
[grub-sysbootlog.txt](https://github.com/gentoojp/issues/files/734499/grub-sysbootlog.txt)
[grub_verboselog.txt](https://github.com/gentoojp/issues/files/734498/grub_verboselog.txt)


[fstab.txt](https://github.com/gentoojp/issues/files/734504/fstab.txt)
[make.conf.txt](https://github.com/gentoojp/issues/files/734503/make.conf.txt)

**Comment by mazgi** [comment]
@i-id targetを指定するように言われているので、やはりBIOS向けにインストールしているにもかかわらず、grubだけUEFI向けに設定しようとしているように見えますね。

まず `/etc/portage/make.conf` を編集して、 ⏬ のような結果になるようにしてみてください。  
(今は `GRUB_PLATFORMS="efi-64"` となっていると思いますので `pc` を加えてください)

### make.confを編集

```shellsession
# grep 'GRUB_PLATFORMS' /etc/portage/make.conf
GRUB_PLATFORMS="efi-64 pc"
```

### grubのパッケージを再インストール

次に ⏬ のように `grub` を再インストールしてください。  
`--ask` や `--verbose` はつけてもつけなくても問題ないですが、今回は `--update` はつけないでください。

```shellsession
# emerge sys-boot/grub:2
```

### grubをboot領域にインストール

次に `grub2-install` `grub2-mkconfig` を ⏬ のように実行してみてください。
つまり、(手前味噌ですが)[この記事](http://qiita.com/mazgi/items/5b059ff6aa4bae22e48e#install-boot-loader)の「BIOS+GPTの場合はこんな感じにする」部分だけを実行してください。

```shellsession
# grub2-install /dev/sda
# grub2-mkconfig -o /boot/grub/grub.cfg
```

## それでもうまくいかない場合

うまくいかない場合はエラーが出た際のコンソール出力と以下のコマンドの実行結果を教えてください。

```shellsession
# fdisk -l /dev/sda
```

**Comment by unarist** [comment]
あー・・・[Handbookに書いてある](https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Bootloader#Emerge)コードを**順番に**実行しちゃったんですね。

先に書いておきます。 @mazgi さんは GRUB_PLATFORM に pc を追加するよう書かれていますが、多分 GRUB_PLATFORM の記述を消したうえでgrubを再インストールしても構いません。

---

Handbookの当該セクションにはBIOS向けとUEFI向けという違う対象に向けた説明が交互に書かれているので、あなたが関係ない方は実行しなくてよいのです。

fdisk周りの記述からBIOS構成だと思うので、あなたが Configuring the bootloader で実行すべきコードはこれだけです。

```
# emerge --ask --verbose sys-boot/grub:2
# grub-install /dev/sda
# grub-mkconfig -o /boot/grub/grub.cfg
```

あなたの場合、**make.confにGRUB_PLATFORMを追加してはいけません**。追加してしまった結果、そのようなエラーが出たという記事を見つけました。 http://linux.overshoot.tv/wiki/grub_install_error_usrlibgrubi386_pcmodinfosh_doesnt_exist

**Comment by mazgi** [comment]
@unarist 

> 追加してしまった結果、そのようなエラーが出たという記事を見つけました。 http://linux.overshoot.tv/wiki/grub_install_error_usrlibgrubi386_pcmodinfosh_doesnt_exist

おお、その情報知りませんでした。
emerge時に `GRUB_PLATFORMS="efi-64* pc* -emu*"` ってなってるので、このwiki書いた方が `pc` 設定していない `GRUB_PLATFORMS` を書いていたのではないかとも思いました。


@i-id 「 `GRUB_PLATFORMS` 書いてください」と「 `GRUB_PLATFORMS` 書かないでください」という2つの意見が同時に発生して混乱してしまったかもしれませんが、もし問題起こったら `/etc/portage/make.conf` から `GRUB_PLATFORMS` の行を消してみてください。
そして `GRUB_PLATFORMS` について編集や行削除をしたら(手間ですが)都度

```shellsession
# emerge sys-boot/grub:2` 
```

を実行してgrubパッケージを再インストールしてください。

**Comment by i-id** [comment]
先ほど再度設定したらインストール出来ました。
再起動してOS起動を確認できました。
ただログインしてみたところネットワークへ接続されていませんでした。
ifconfig -a 実行してもlanアダプタが表示させないので、再度設定からやり直してみます。
ありがとうございました！
