### ISSUE TITLE
ネットワークの設定について

### ISSUE THREAD

**Issue by i-id** [gentoojp/issues#9]
いつも大変お世話になっております。
インストールマニュアル手順通りに進めて完了しましたが、再起動後ネットワークへの接続ができませんでした。
再度マニュアルを参照しながら設定を試みましたがうまくいきませんでした。
makeconfigでネットワークカードのドライバーを再度指定（同メーカー全て指定）し
make && make modules_installを実施し再起動させても解決できずにいます。
(ipconfig -aで表示すらされません）

BootCD(USBメモリ)では読み込まれて動作しますので、BootCDで読み込まれてるドライバーを調べて同じものを設定すれば良いかと思い探してみましたが見つけられませんでした。

どのようにすれば解決できるのか教えていだけでないでしょうか。
このような質問ばかりで申し訳ありません。
開示すべき情報も合わせて教えてください。

**Comment by mazgi** [comment]
機種は #7 と同じですよね。
仕様これですかね。
https://www.sony.jp/vaio/pre_include/html/Z21/spec_vom1_biz.html
(予想通りですが) `1000BASE-T/100BASE-TX/10BASE-T ×1` としか書いてないですね。

CD(USBメモリ)でブートして(NICドライバが読めている状態で) dmesgを `net` や `ether` でgrepした結果を貼っていただくと何かわかるかもしれません。
⏬ みたいな感じです。

```shellsession
# dmesg | grep -i net
[    0.000000] DMI: SAKURA Internet Inc. SAKURA CLOUD KVM, BIOS 2.4 06/30/2016
[    0.020000] Initializing cgroup subsys net_cls
[    0.020000] Initializing cgroup subsys net_prio
[    0.150690] NET: Registered protocol family 16
[    1.259922] NET: Registered protocol family 2
[    1.262991] NET: Registered protocol family 1
[    1.588268] audit: initializing netlink subsys (disabled)
[    1.925366] e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[    1.926877] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    1.934658] NET: Registered protocol family 17
[    1.937523] microcode: Microcode Update Driver: v2.01 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
[    2.609078] FS-Cache: Netfs 'nfs' registered for caching
[    2.631677] igb: Intel(R) Gigabit Ethernet Network Driver - version 5.3.0-k
[    7.118749] NET: Registered protocol family 10
# dmesg | grep -i ether
[    2.631677] igb: Intel(R) Gigabit Ethernet Network Driver - version 5.3.0-k
```

あとは `menuconfig` するときに `Device Drivers > Network device support > Ethernet driver support` を全部 `*` つけてみるという手もあります。
⏬ の画面です。

<img width="1440" alt="screen shot 2017-01-31 at 18 57 40" src="https://cloud.githubusercontent.com/assets/194222/22460203/3804638a-e7e7-11e6-979d-5f43afaa5c3b.png">

**Comment by i-id** [comment]
mazgi さん
いつもありがとうございます。
教えて頂いた手順で実行してみました。
１、dmesg | grep -i netで表示されたドライバーを選択してmodules_install →　NG
２、make menuconfigにてsupport表示されたドライバー全て選択　→　NG
３、make menuconfigにてすべてのドライバーを選択　→　NG

1番の手順で表示された画面のキャプチャーを添付します。
お手数をおかけしますがよろしくお願いします。
![20170131_102232063_ios](https://cloud.githubusercontent.com/assets/12995326/22463663/1c3820a6-e7f6-11e6-8c51-dfb43238b61f.jpg)

**Comment by mazgi** [comment]
ちなみにlspciって実行できないですよね・・

**Comment by i-id** [comment]
実行してみました。
![img_0467](https://cloud.githubusercontent.com/assets/12995326/22463869/721f2dd8-e7f7-11e6-9962-3b4c240b591f.JPG)

**Comment by mazgi** [comment]
Realtekの RTL8111/8168/8411 って書いてますね
(そして `Intel Corporation Centrino Advanced– N WiMAX6250` というのがWiFi)

**Comment by i-id** [comment]
ドライバーは認識されているのにインストールされていないということでしょうか。
ifconfig -a でも表示されないので別にnano -w /etc/conf.d/modulesに記述が必要ということでしょうか。

**Comment by mazgi** [comment]
> ドライバーは認識されているのにインストールされていない

ドライバ自体がインストールされていないのではないでしょうか
`Device Drivers → Network device support → Ethernet driver support` の `Realtek devices` あたりに `*` が付いていなければつけてみるとNICが認識されたりしませんか?

<img width="1440" alt="screen shot 2017-01-31 at 21 03 30" src="https://cloud.githubusercontent.com/assets/194222/22467725/10f9486a-e809-11e6-839f-3b9ff9567555.png">

**Comment by aliceinwire** [comment]
@i-id lsmodのコマンド結果を見せてください

**Comment by i-id** [comment]
mazgi さん
![img_0470](https://cloud.githubusercontent.com/assets/12995326/22468409/839c85e2-e80b-11e6-86da-28c467e8065b.JPG)

Aliceさん
![img_0469](https://cloud.githubusercontent.com/assets/12995326/22468457/afaef58e-e80b-11e6-86f3-fdeb42f44e6b.JPG)

**Comment by mazgi** [comment]
@i-id この状態で modules_install までして再起動してもNICが見えないですか?

**Comment by mazgi** [comment]
あー・・
`emerge r8168` するとどうでしょう?
https://packages.gentoo.org/packages/net-misc/r8168

**Comment by i-id** [comment]
mazgi さん

![20170131_142707336_ios](https://cloud.githubusercontent.com/assets/12995326/22468876/5cdf9f8c-e80d-11e6-98a8-b9a36b6f0ad4.jpg)
![20170131_142852954_ios](https://cloud.githubusercontent.com/assets/12995326/22468875/5cd20174-e80d-11e6-8c3a-f522fc5a0a03.jpg)

**Comment by stkchp** [comment]
wifiの方はおそらくlinux-firmwareが必要です。

```
emerge sys-kernel/linux-firmware
```

firmwareが必要な場合、network driverをkernel組み込みではなく、moduleとしてbuildすることが必須のものもあります。r8169の方も同じようにmoduleとしてのbuildが必要なのかもしれません。

参考までに私のPCは以下のように選択してます。
 
環境
![2017-01-31 23 49 42](https://cloud.githubusercontent.com/assets/19767799/22470177/c65d46cc-e811-11e6-8f2c-077a6d62526a.png)

Realtek
![2017-01-31 23 51 24](https://cloud.githubusercontent.com/assets/19767799/22470027/3fbaa5ec-e811-11e6-8c6b-9a352caf9973.png)

Intel Wifi
![2017-01-31 23 51 42](https://cloud.githubusercontent.com/assets/19767799/22470032/423fb6f4-e811-11e6-8c28-dc3e6023d8dd.png)

**Comment by mazgi** [comment]
@i-id `r8168` を `r8186` とtypoしてますね。
( `there are no ebuilds to satisfy "r8186". Maybe you meant net-misc/r8168?` と言われています)

1. 正しいパッケージ名で emerge し直して
1. `modprobe r8168` して
1. `lsmod | grep r81`  の結果を教えてください。

**Comment by i-id** [comment]
mazgi さん
再度emergeを実行したところエラーとなってしまいました。

![20170131_164919190_ios](https://cloud.githubusercontent.com/assets/12995326/22474999/0482efba-e821-11e6-9422-1704332dd770.jpg)
![20170131_164753063_ios](https://cloud.githubusercontent.com/assets/12995326/22474998/0482bfc2-e821-11e6-939e-e3f85934144a.jpg)

**Comment by i-id** [comment]
stkchp さん
linux-firmwareを実行しました。
この後のmoduleとしてbuildすることについてですが、
マニュアルのカーネルモジュール・カーネルの設定の部分であっていますか？
https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Kernel/ja

あっていた場合、ここで追記するmodules=の後に記述する内容はlspciで表示されたドライバー全てを入力する必要がありますか？
短縮したものがあるのでしたら、どこでわかりますか？

**Comment by aliceinwire** [comment]
@i-id https://wiki.gentoo.org/wiki/Wifi/ja

**Comment by aliceinwire** [comment]
@i-id ちなみにnet-misc / r8168インストールしたいなら
カーネルのCONFIG_R8169 はチェック外してください

**Comment by stkchp** [comment]
@i-id さん

> この後のmoduleとしてbuildすることについてですが、
> マニュアルのカーネルモジュール・カーネルの設定の部分であっていますか？
> https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Kernel/ja

はい、あっています。
ドライバは`lspci`で出てきたものを全てmoduleとしてビルドする必要はありません。
@i-idさんの`lspci`結果を見る限り、私が例に上げた画像のrealtekとIntel Wifiの部分の設定と同じでいいと思います。

NICが認識されない場合dmesgにwarn等出てるはずので、それも貼り付けて貰えればトラブルシューティングし易いです

**Comment by i-id** [comment]
設定をして再起動しました。
ＯＳ選択後、画面が黒くなり起動しているのかわからない状態になってしまいました。
何度再起動しても同じ現象なので、bootCDから再度設定をし直してみます。
みなさんから頂いたアドバイスへの返答まで少々お時間下さい。

**Comment by unarist** [comment]
前のカーネルを残しておくと、カーネルの設定に失敗したときでも、ブートメニューでそれを選択することでとりあえず起動できることがあります。

もしCDからやり直すならおまけ情報として、lspci -kやethtool
-i（LiveCDにはないかも）などで、ネットワークカードに現在使われているドライバを調べることができます。多分ここまでに他の方が指摘されてるやつだとは思いますが…。
参考 http://d.hatena.ne.jp/rx7/20140121/p1

**Comment by i-id** [comment]
皆様のおかげで無事ネットワーク接続を確認できました。
数日にわたりサポート頂きましてありがとうございました！
